### ISSUE TITLE
 Cannot find name 'unknown'.

### ISSUE THREAD

**Issue by workfel** [ngxs-labs/dispatch-decorator#104]
Hi, 

I have some problem during launch my app.

I use `@ngxs/store : 3.4.2` and `@ngxs-labs/dispatch-decorator : 1.1.0` and `Angular: 6.1.3`
When i `serve` the app i have this error 
```
ERROR in node_modules/@ngxs-labs/dispatch-decorator/lib/core/actions/actions.d.ts(4,41): error TS2304: Cannot find name 'unknown'.
```
This is the `actions.d.ts` file

```ts
/**
 * This class is used as a default action when the user doesn't pass any custom action as an argument
 */
export declare class DispatchAction<T = unknown> {
    payload?: T | undefined;
    /**
     * Action type
     */
    static type: string | null;
    /**
     * Creates DispatchAction instance
     *
     * @param payload - Data to dispatch
     */
    constructor(payload?: T | undefined);
}
````

So, for solving it during my dev, i have replaced `unknow` by `any`.

How can solve this without changing the code in node_modules ? 

Thx

**Comment by splincode** [comment]
Upgrade to TypeScript 3+

**Comment by workfel** [comment]
Work fine, thank you

**Comment by vmuresanu** [comment]
But what if I have project limitation to use angular 6 which has angular compiler 6, which uses Typescript 2.7.2 - 2.10.0. Do we have a chance using ngxs dispatch-decorator with older typescript versions? Or only 3+?
