### ISSUE TITLE
Calling dispatch decorator

### ISSUE THREAD

**Issue by smarteez17** [ngxs-labs/dispatch-decorator#332]
Hi there currently I am dispatching a call on a selectedchange event as below 

 private GetReportingPeriod(finYearId: string) {
    this.store.dispatch(new GetReportingPeriod( { financialYearId: finYearId}));
  }

How do I used the dispatch decorator so that i dont need to inject store any more

**Comment by splincode** [comment]
```ts
@Dispatch() 
private getReportingPeriod(financialYearId: string): GetReportingPeriod {
 return new GetReportingPeriod({ financialYearId });
}
```

**Comment by smarteez17** [comment]
thanks
