### ISSUE TITLE
Actions dispatched using the decorator cannot be consumed as observables/promises

### ISSUE THREAD

**Issue by ConnorJBeck** [ngxs-labs/dispatch-decorator#367]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

(not sure if behaviour already exists, is supposed to exist, or is not planned to exist)

## Current behavior
There doesn't appear to be a way to wait for a dispatched action, which itself subscribes to an observable, to complete when using the @Dispatch decorator, though it is possible by injecting the store.

## Expected behavior
Being able to async/await on a dispatched action with asynchronous behaviour when using the dispatch decorator.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngxs-dispatch-decorator-async

1. Open the stackblitz console
2. Click the first button. Notice that there is a delay of 1 second, then the count is updated in the page to 1 and the console logs 1
3. Click the second button. Notice that the console immediately logs 1 and the count is not updated until a second later, so they are out of sync.

## What is the motivation / use case for changing the behavior?
This behaviour works when using the standard injection style, and as we move towards using the annotation exclusively for cleaner code, I'd prefer to not have certain use cases where I must inject the store.

## Environment

<pre><code>
Libs:
- @angular/core version: latest
- @ngxs/store version: latest

</code></pre>

**Comment by arturovt** [comment]
> Being able to async/await on a dispatched action with asynchronous behaviour when using the dispatch decorator.

This is incorrect behavior. You're using `await` operator with a function that retuns `new Add()`, how do you expect it to behave? V8 just wraps `new Add()` into `Promise` but it has nothing to do with waiting for this action to complete.

Also assuming that this method is patched under the hood to return a `Promise` then how are you going to make TypeScript be friendly with it?
```ts
class T {
  @Dispatch() func = () => new Action();

  async method1() {
    await this.func(); // ok
  }

  method2() {
    this.func().then(...); // compilation error as `Action` type is inferred
  }
}
```

That is how it should look like:
```ts
this.add();
await this.actions$.pipe(ofActionSuccessful(Add), take(1)).toPromise();
const number = this.store.selectSnapshot(CountState);
console.log(number);
```

**Comment by ConnorJBeck** [comment]
I can't believe I never thought of waiting on the `ofActionSuccessful` event... makes complete sense. It still would be nice visually for `this.add()` to return a promise that you could then wait on or hook a callback to, but I understand if there are technical reasons it's not appropriate. I'll be honest, I'm still fairly amateur when it comes to typescript so I don't see an issue that would crop up in your example that couldn't be worked around - the Dispatch operator itself is essentially magic as far as I'm concerned.

Thanks for the response and the clarification.
