### ISSUE TITLE
Angular 11

### ISSUE THREAD

**Issue by ckorherr** [ngxs-labs/dispatch-decorator#501]
Using this package with Angular 11 I get following warning:
`npm WARN @ngxs-labs/dispatch-decorator@2.1.0 requires a peer of @angular/core@>=7.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.`

Is this package still supported and will there be an update?

**Comment by IJsbrandVV** [comment]
@arturovt @splincode It looks like the maintenance bot fixed this issue, can one of you publish a new version to NPM please?

**Comment by arturovt** [comment]
I've published `2.1.1` version. Sorry, I wish we could have time to support this package.

**Comment by IJsbrandVV** [comment]
No problem. Thanks a bunch for publishing the new version @arturovt

**Comment by arturovt** [comment]
Can we close the issue?
