### ISSUE TITLE
Angular 12

### ISSUE THREAD

**Issue by ckorherr** [ngxs-labs/dispatch-decorator#533]
Could someone release a new version with the updated dependencies for Angular 12?

**Comment by markwhitfeld** [comment]
@splincode could you have a look at this?

**Comment by marioese31** [comment]
Hi @arturovt, could you please help out?
Big fan and a new version would greatly help us migrate to NG12...  Thanks in advance!

**Comment by arturovt** [comment]
Hey, I've published v3.0.0.
