### ISSUE TITLE
Problem accessing base class properties from derived Component class

### ISSUE THREAD

**Issue by nzacca** [ngxs-labs/dispatch-decorator#72]
Hello!

There appears to be an issue when accessing base class properties from a Dispatch handler defined in a derived Component class. 

The target that is passed to the original function is the base class instead of the derived class.
https://github.com/ngxs-labs/dispatch-decorator/blob/master/src/lib/core/decorators/dispatch.ts#L75

If I change `target` to `this`, everything works as expected.

Here is a demo of the issue I'm seeing: https://stackblitz.com/edit/ngxs-starter-w9pjpj?file=app%2Fhello.component.ts

Is this a bug or expected behavior?

Thank you!

**Comment by splincode** [comment]
create pull request and add tests for fix it

**Comment by splincode** [comment]
This is bug
https://github.com/ngxs-labs/dispatch-decorator/issues/70

**Comment by arturovt** [comment]
@nzacca `1.3.0`
